services:
  settings-example-php:
    image: php:8.3-fpm
    volumes:
      - ./:/var/www/settings-example
      - ../settings-bundle:/var/www/settings-bundle
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=host.docker.internal"

  settings-example-web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/settings-example
      - ./docker/nginx-site.conf:/etc/nginx/conf.d/default.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']