controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

tzunghaor_settings:
  resource: '@TzunghaorSettingsBundle/config/routes.xml'
  prefix: '/settings'